#!/bin/bash
set -e

echo "Post install script of capslock-auto-switch"
echo "  Enabling and starting service for $SUDO_USER"

systemctl --machine="$SUDO_USER@.host" --user daemon-reload
systemctl --machine="$SUDO_USER@.host" --user enable capslock-auto-switch
systemctl --machine="$SUDO_USER@.host" --user start capslock-auto-switch
