#!/bin/bash
set -e
echo "Post install script of capslock-auto-switch"
echo "Enabling and starting service for "$SUDO_USER
deb-systemd-invoke --machine=$SUDO_USER@ --user daemon-reload
deb-systemd-invoke --machine=$SUDO_USER@ --user enable capslock-auto-switch 
deb-systemd-invoke --machine=$SUDO_USER@ --user start capslock-auto-switch                                                                                                                                                                                            
