name: Build debian package

on:
  push:
    branches:
      - main

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev xorg-dev libxdo-dev

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo test
        run: cargo test

      - name: Cargo build
        run: cargo build --release

      - name: Create debian package
        run: ./debian-build.sh
