name: Build debian package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev xorg-dev libxdo-dev

      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo test
        run: cargo test

      - name: cargo build
        run: cargo build --release
