name: release

on:
  release:
    types: [created]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build-ok:
    uses: ./.github/workflows/build.yml

  build-asset-release:
    runs-on: ubuntu-latest
    needs: build-ok
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: nowsprinting/check-version-format-action@v4.0.1
        id: version
        with:
          prefix: "v"

      - name: Replace tag
        run: |
          TAG=${{ steps.version.outputs.full_without_prefix }}
          echo "Replacing tag with $TAG"
          sed -i "s/^\(version\s*=\s*\"\).*\(\".*\)$/\1$TAG\2/" "Cargo.toml"
          sed -i "s/^\(VERSION\s*=\s*\"\).*\(\".*\)$/\1$TAG\2/" "debian-build.sh"
          sed -i "s/^\(Version\s*:\s*\).*\(.*\)$/\1$TAG\2/" "debian/DEBIAN/control"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev xorg-dev libxdo-dev

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Create debian package
        run: ./debian-build.sh

      - name: Commit & Push changes
        uses: actions-js/push@master@v1.4
        with:
          message: "🔖 auto update version 🤖"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: capslock*.deb
